apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: elastic-cluster
  namespace: elastic-system
spec:
  type: heartbeat
  version: 8.12.0
  elasticsearchRef:
    name: elastic-cluster
  config:
    heartbeat.monitors:
    - type: http
      id: Google-beat
      name: Google
      service.name: Google
      hosts: ["https://google.com"]
      check.response.status: [200, 301]
      schedule: '@every 5s'
      tags: ["Google"]

  deployment:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        securityContext:
          runAsUser: 0